steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-image', '-f', 'apps/program-refresh/Dockerfile', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-image']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'jobs', 'deploy', 'program-job', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-image', '--region', '$LOCATION']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-image'
options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
