steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_PROJECT_ID}-repo/program-refresh-image', '-f', 'apps/program-refresh/Dockerfile', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_PROJECT_ID}-repo/program-refresh-image']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'jobs', 'deploy', 'program-refresh-job', '--image', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_PROJECT_ID}-repo/program-refresh-image', '--region', '${_LOCATION}']
images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_PROJECT_ID}-repo/program-refresh-image'
substitutions:
  _PROJECT_ID: $PROJECT_ID
  _LOCATION: $LOCATION_ID
options:
  logging: CLOUD_LOGGING_ONLY
