steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION_ID-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-refresh-image', '-f', 'apps/program-refresh/Dockerfile', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$LOCATION_ID-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-refresh-image']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'jobs', 'deploy', 'program-refresh-job', '--image', '$LOCATION_ID-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-refresh-image', '--region', '$LOCATION_ID']
images:
- '$LOCATION_ID-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-repo/program-refresh-image'
options:
  logging: CLOUD_LOGGING_ONLY
